name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Building Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag  developitl/expenses-api-transactions:${{ github.run_number }}
        docker save developitl/expenses-api-transactions:${{ github.run_number }} -o expenses-api-transactions.tar
    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-artifact
        path: expenses-api-transactions.tar
  push:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image-artifact
    - name: Load Docker Image
      run: |
        docker load -i expenses-api-transactions.tar
        docker images
    - uses: docker/login-action@v3.5.0
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASWORD }}
    - name: Push image to Docekr Hub
      run: docker push developitl/expenses-api-transactions:${{ github.run_number }}
